apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: controller-orderer1
  namespace: controller-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: controller-orderer1
  chart:
    git: https://github.com/ayhamkassab/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: controller-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    orderer:
      name: orderer1
      loglevel: info
      localmspid: controllerMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: kafka

    storage:
      storageclassname: controllersc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://130.104.229.14:30000
      role: vault-role
      authpath: controller-net-auth
      secretprefix: secret/crypto/ordererOrganizations/controller-net/orderers/orderer1.controller-net
      imagesecretname: regcred
      serviceaccountname: vault-auth
    kafka:
      readinesscheckinterval: 10
      readinessthreshold: 10
      brokers:
      - kafka-0.broker.controller-net.svc.cluster.local:9092
      - kafka-1.broker.controller-net.svc.cluster.local:9092
      - kafka-2.broker.controller-net.svc.cluster.local:9092

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      
