name: Fabric
    version: "2.0.0"

    caliper:
      blockchain: fabric
      #sutOptions:
      #  mutualTls: false
      #fabric:
      #  gateway:
      #    usegateway: true
      #    discovery: true

    info:
      Orderer: Kafka
      Version: 2.2.0
      Distribution: Single Host
      StateDB: CouchDB
      Size: 3 Orgs

    channels:
      - channelName: allchannel
        create:
          buildTransaction:
            capabilities: []
            consortium: 'SupplyChainConsortium'
            msps: ['carrierMSP', 'manufacturerMSP']
            version: 0
        contracts:
        - id: simpleauction
          contractID: simpleauction
          install:
            language: golang
            version: "v1"
            path: simpleauction/
          instantiate:
            initFunction: init
          initArguments: []
          created: true

    organizations:
      - mspid: carrierMSP
        identities:
          certificates:
          - name: 'admin'
            admin: true
            clientPrivateKey:
              pem: |
                -----BEGIN PRIVATE KEY-----
                MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwPfZB/w1xtPVZ9BI
                RlZ1ZGaY3pJaAg6FppieS3wiMuyhRANCAATMKAgY55WECkMKXKIqcrz/5HLx+pVI
                b7Qszx1RHgTnLcxvQlXtS9otEVRHxfCDQf+JAAQZw2JS5g7Mkaoag13c
                -----END PRIVATE KEY-----
            clientSignedCert:
              pem: |
                -----BEGIN CERTIFICATE-----
                MIIC8DCCApagAwIBAgIUCfcstAOMgi04KoVyyUkL13o3b/EwCgYIKoZIzj0EAwIw
                WjELMAkGA1UEBhMCR0IxDzANBgNVBAgMBkxvbmRvbjEPMA0GA1UEBwwGTG9uZG9u
                MRAwDgYDVQQKDAdDYXJyaWVyMRcwFQYDVQQDDA5jYS5jYXJyaWVyLW5ldDAeFw0y
                MTAzMTYxNTQ5MDBaFw0yMjAzMTYxNTU0MDBaMHkxCzAJBgNVBAYTAkdCMRswGQYD
                VQQHExI1MS41MC8tMC4xMy9Mb25kb24xEDAOBgNVBAoTB0NhcnJpZXIxHzANBgNV
                BAsTBmNsaWVudDAOBgNVBAsTB0NhcnJpZXIxGjAYBgNVBAMMEUFkbWluQGNhcnJp
                ZXItbmV0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzCgIGOeVhApDClyiKnK8
                /+Ry8fqVSG+0LM8dUR4E5y3Mb0JV7UvaLRFUR8Xwg0H/iQAEGcNiUuYOzJGqGoNd
                3KOCARkwggEVMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
                BBTnq4fnD/dccc2drK5XTBPE1uFgQjAfBgNVHSMEGDAWgBSrvolpo75acgRxjMaY
                LikkM4YiejAkBgNVHREEHTAbghljYS10b29scy03OTg1ODlmOWQ1LWI2a3pmMIGO
                BggqAwQFBgcIAQSBgXsiYXR0cnMiOnsiYWJhYy5pbml0IjoidHJ1ZSIsImFkbWlu
                IjoidHJ1ZSIsImhmLkFmZmlsaWF0aW9uIjoiQ2FycmllciIsImhmLkVucm9sbG1l
                bnRJRCI6IkFkbWluQGNhcnJpZXItbmV0IiwiaGYuVHlwZSI6ImNsaWVudCJ9fTAK
                BggqhkjOPQQDAgNIADBFAiEA8E76T01VRjW4s9Sz1oy47LpwdcZlfHeyFBjYszOY
                yiICIBVf4C/ifDHkSOM3SiADSfluHMMSY/EXThFpzcnXu9z8
                -----END CERTIFICATE-----
        connectionProfile:
          path: './Org1ConnectionProfile.json'
          discover: true
      - mspid: manufacturerMSP
        identities:
          certificates:
          - name: 'admin'
            admin: true
            clientPrivateKey:
              pem: |
                -----BEGIN PRIVATE KEY-----
                MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgW930lITUrRWKIG6i
                fJnX4chQRs8i2Y/xFtvhxBv56WehRANCAASGq29gLm+KkET9zalLdBdS1C+RSeb4
                qtIKTuSHje11P8veAUx7bUDd1o9kSRv4qh7unN28IvyPvxvCmLn46q8N
                -----END PRIVATE KEY-----
            clientSignedCert:
              pem: |
                -----BEGIN CERTIFICATE-----
                MIIDEzCCArmgAwIBAgIUQggGE4VW2n1VcMd9tTZQ/6u+tjIwCgYIKoZIzj0EAwIw
                ZDELMAkGA1UEBhMCQ0gxDzANBgNVBAgMBlp1cmljaDEPMA0GA1UEBwwGWnVyaWNo
                MRUwEwYDVQQKDAxNYW51ZmFjdHVyZXIxHDAaBgNVBAMME2NhLm1hbnVmYWN0dXJl
                ci1uZXQwHhcNMjEwMzE2MTU0ODAwWhcNMjIwMzE2MTU1MzAwWjCBhzELMAkGA1UE
                BhMCQ0gxGjAYBgNVBAcTETQ3LjM4LzguNTQvWnVyaWNoMRUwEwYDVQQKEwxNYW51
                ZmFjdHVyZXIxJDANBgNVBAsTBmNsaWVudDATBgNVBAsTDE1hbnVmYWN0dXJlcjEf
                MB0GA1UEAwwWQWRtaW5AbWFudWZhY3R1cmVyLW5ldDBZMBMGByqGSM49AgEGCCqG
                SM49AwEHA0IABIarb2Aub4qQRP3NqUt0F1LUL5FJ5viq0gpO5IeN7XU/y94BTHtt
                QN3Wj2RJG/iqHu6c3bwi/I+/G8KYufjqrw2jggEjMIIBHzAOBgNVHQ8BAf8EBAMC
                B4AwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUGr4LvRKcW4Msss2fw7F0/ONXp1sw
                HwYDVR0jBBgwFoAUXqh0+IpI/TTUg1k/ZpdpVB0mrBgwJAYDVR0RBB0wG4IZY2Et
                dG9vbHMtNzk4NTg5ZjlkNS1tbWdtbTCBmAYIKgMEBQYHCAEEgYt7ImF0dHJzIjp7
                ImFiYWMuaW5pdCI6InRydWUiLCJhZG1pbiI6InRydWUiLCJoZi5BZmZpbGlhdGlv
                biI6Ik1hbnVmYWN0dXJlciIsImhmLkVucm9sbG1lbnRJRCI6IkFkbWluQG1hbnVm
                YWN0dXJlci1uZXQiLCJoZi5UeXBlIjoiY2xpZW50In19MAoGCCqGSM49BAMCA0gA
                MEUCIQDp4gVafPDmC/CLZmFiAFR8DW0Fo2BEVWI35eW22M4WIwIgbomhFGGEKDOE
                rj5stYgpZQ31+cRyq37dHPZSKJBscuY=
                -----END CERTIFICATE-----
        connectionProfile:
          path: './Org2ConnectionProfile.json'
          discover: true