name: Fabric
    version: "2.0.0"

    caliper:
      blockchain: fabric
      sutOptions:
        mutualTls: true
      fabric:
        gateway:
          usegateway: true
          discovery: true

    info:
      Orderer: Kafka
      Version: 2.2.0
      Distribution: Single Host
      StateDB: CouchDB
      Size: 3 Orgs

    channels:
      - channelName: mychannel
        create:
          buildTransaction:
            capabilities: []
            consortium: 'SampleConsortium'
            msps: ['carrierMSP', 'manufacturerMSP']
            version: 0
        contracts:
        - id: simpleauction
          contractID: simpleauction
          install:
            language: golang
            version: "v1"
            path: simpleauction/
          instantiate:
            initFunction: init
          initArguments: []
          created: true

    organizations:
      - mspid: carrierMSP
        identities:
          certificates:
          - name: 'admin'
            admin: true
            clientPrivateKey:
              path: secret/carrier//admin/msp/keystore/server.pem
            clientSignedCert:
              path: secret/carrier/admin/msp/signcerts/server.pem
        connectionProfile:
          path: './Org1ConnectionProfile.json'
          discover: true
      - mspid: manufacturerMSP
        identities:
          certificates:
          - name: 'admin'
            admin: true
            clientPrivateKey:
              path: secret/manufacturer/admin/msp/keystore/server.pem
            clientSignedCert:
              path: secret/manufacturer/admin/msp/signcerts/server.pem
        connectionProfile:
          path: './Org2ConnectionProfile.json'
          discover: true