name: Fabric
    version: "2.0.0"

    caliper:
      blockchain: fabric
      sutOptions:
        mutualTls: false
      fabric:
        gateway:
          usegateway: true
          discovery: true

    info:
      Orderer: Kafka
      Version: 2.2.0
      Distribution: Single Host
      StateDB: CouchDB
      Size: 3 Orgs

    channels:
      - channelName: allchannel
        create:
          buildTransaction:
            capabilities: []
            consortium: 'SupplyChainConsortium'
            msps: ['carrierMSP', 'manufacturerMSP']
            version: 0
        contracts:
        - id: simpleauction
          contractID: simpleauction
          install:
            language: golang
            version: "v1"
            path: simpleauction/
          instantiate:
            initFunction: init
          initArguments: []
          created: true

    organizations:
      - mspid: carrierMSP
        identities:
          certificates:
          - name: 'admin'
            admin: true
            clientPrivateKey:
              path: secret/tls/admin.pem
            clientSignedCert:
              path: secret/tls/admin.cert
        connectionProfile:
          path: './Org1ConnectionProfile.yaml'
          discover: true
      - mspid: manufacturerMSP
        identities:
          certificates:
          - name: 'admin'
            admin: true
            clientPrivateKey:
              path: secret/tls/admin.pem
            clientSignedCert:
              path: secret/tls/admin.cert
        connectionProfile:
          path: './Org2ConnectionProfile.yaml'
          discover: true