---
    rateControl: &rate
      type: fixed-rate
      opts:
        tps: 20

    test:
      name: simpleauction
      description: simpleauction benchmark for evaluating create, modify, and query operations.
      workers:
        type: local
        number: 4
      rounds:
        - label: create
          txNumber: 500
          rateControl: *rate
          workload:
              module: createOffer.js
        - label: bids
          txNumber: 500
          rateControl: *rate
          workload:
            module: createBid.js

    monitors:
        resource:
        - module: docker
          options:
            interval: 1
            containers: ['all']