info:
  Orderer: Kafka
  Version: 2.2.0
  Distribution: Single Host
  StateDB: CouchDB
  Size: 3 Orgs
organizations:
- identities:
    certificates:
    - admin: true
      clientPrivateKey:
        path: secret/carrier/tls/admin.pem
      clientSignedCert:
        path: secret/carrier/tls/admin.cert
      name: "admin"
  connectionProfile:
    path: "./carrierConnectionProfile.yaml"
    discover: True
  mspid: carrierMSP
- identities:
    certificates:
    - admin: true
      clientPrivateKey:
        path: secret/manufacturer/tls/admin.pem
      clientSignedCert:
        path: secret/manufacturer/tls/admin.cert
      name: "admin"
  connectionProfile:
    path: "./manufacturerConnectionProfile.yaml"
    discover: True
  mspid: manufacturerMSP
- identities:
    certificates:
    - admin: true
      clientPrivateKey:
        path: secret/buyer/tls/admin.pem
      clientSignedCert:
        path: secret/buyer/tls/admin.cert
      name: "admin"
  connectionProfile:
    path: "./buyerConnectionProfile.yaml"
    discover: True
  mspid: buyerMSP
- identities:
    certificates:
    - admin: true
      clientPrivateKey:
        path: secret/windowshopper/tls/admin.pem
      clientSignedCert:
        path: secret/windowshopper/tls/admin.cert
      name: "admin"
  connectionProfile:
    path: "./windowshopperConnectionProfile.yaml"
    discover: True
  mspid: windowshopperMSP
- identities:
    certificates:
    - admin: true
      clientPrivateKey:
        path: secret/dealer/tls/admin.pem
      clientSignedCert:
        path: secret/dealer/tls/admin.cert
      name: "admin"
  connectionProfile:
    path: "./dealerConnectionProfile.yaml"
    discover: True
  mspid: dealerMSP
name: Fabric
caliper:
  sutOptions:
    mutualTls: false
  blockchain: fabric
  fabric:
    gateway:
      usegateway: true
      discovery: true
channels:
- contracts:
  - initArguments: []
    created: true
    instantiate:
      initFunction: init
    install:
      path: simpleauction/
      version: "v1"
      language: golang
    endorsementPolicy:
      policy:
        5-of:
        - signed-by: 0
        - signed-by: 1
        - signed-by: 2
        - signed-by: 3
        - signed-by: 4
      identities:
      - role:
          name: member
          mspId: carrierMSP
      - role:
          name: member
          mspId: manufacturerMSP
      - role:
          name: member
          mspId: buyerMSP
      - role:
          name: member
          mspId: windowshopperMSP
      - role:
          name: member
          mspId: dealerMSP
    id: simpleauction
    contractID: simpleauction
  create:
    buildTransaction:
      version: 0
      consortium: "SupplyChainConsortium"
      capabilities: []
      msps: ["carrierMSP", "manufacturerMSP", "buyerMSP", "windowshopperMSP", "dealerMSP"]
  channelName: allchannel
version: "2.0.0"
