domain_name: svc.cluster.local
pathToBAF: /root/hyperledger-labs/myFork/blockchain-automation-framework
cloud_provider: minikube

BAFChaincodePath: examples/supplychain-app/fabric/chaincode_rest_server/chaincode/

BAFgitops:
  git_protocol: "https"
  git_url: "github.com/ayhamkassab/blockchain-automation-framework.git"  # Gitops ssh url for flux value files 
  branch: "master"                                                                 # Git branch where release is being made
  release_dir: "platforms/hyperledger-fabric/releases/dev"                        # Relative Path in the Git repo for flux sync per environment. 
  chart_source: "platforms/hyperledger-fabric/charts"                             # Relative Path where the Helm charts are stored in Git repo
  git_repo: "github.com/ayhamkassab/blockchain-automation-framework.git"       # Gitops https URL for git push  (without https://)
  username: "ayhamkassab"                                                     # Git user who has rights to check-in in all branches
  password: "**Ak47**"   
  email: "github_email"                                                           # Email to use in git config
  private_key: "/root/hyperledger-labs/myFork/blockchain-automation-framework/build/gitops"   #this is replaced by pathToBAF/build/gitopts            # Path to private key file which has write-access to the git repo

BAFk8s:
  context: "local"
  config_file: "~/.kube/config"

vault:
  url: "http://130.104.229.14:30000"
  root_token: "s.5KkfEk3Upun8A1fQr1PfjRWL"


organizations:
- id: 1
  name: carrier
  orderer: supplychain
  numberOfPeers: 2 #if 0 then endorser should be false 
  endorser: true #if false then numberOfPeers should be 0 (even if not, the script will count it as 0)

- id: 2
  name: manufacturer
  orderer: supplychain
  numberOfPeers: 1
  endorser: true




- id: 3
  name: buyer
  orderer: supplychain
  numberOfPeers: 4
  endorser: true

- id: 4
  name: supplychain
  orderer: supplychain
  numberOfPeers: 1
  endorser: false

