domain_name: svc.cluster.local

BAFgitops:
  git_protocol: "https"
  git_url: "https://github.com/ayhamkassab/blockchain-automation-framework.git"  # Gitops ssh url for flux value files 
  branch: "master"                                                                 # Git branch where release is being made
  release_dir: "platforms/hyperledger-fabric/releases/dev"                        # Relative Path in the Git repo for flux sync per environment. 
  chart_source: "platforms/hyperledger-fabric/charts"                             # Relative Path where the Helm charts are stored in Git repo
  git_repo: "github.com/ayhamkassab/blockchain-automation-framework.git"       # Gitops https URL for git push  (without https://)
  username: "ayhamkassab"                                                     # Git user who has rights to check-in in all branches
  password: "**Ak47**"   
  email: "github_email"                                                           # Email to use in git config
  private_key: "/root/hyperledger-labs/myFork/blockchain-automation-framework/build/gitops"               # Path to private key file which has write-access to the git repo

BAFk8s:
  context: "local"
  config_file: "~/.kube/config"

vault:
  url: 'http://130.104.229.21:30000'
  root_token: 's.32JqFMwzbrqbeFl8bKI9R2QC'


organizations:
- id: 1
  name: carrier
  orderer: supplychain
  numberOfPeers: 1

- id: 2
  name: manufacturer
  orderer: supplychain
  numberOfPeers: 1

- id: 3
  name: supplychain
  orderer: supplychain
  numberOfPeers: 1


- id: 4
  name: buyer
  orderer: supplychain
  numberOfPeers: 1

