apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caliper.fullname" . }}--caliper
  labels:
    app.kubernetes.io/name: {{ include "caliper.name" . }}
    helm.sh/chart: {{ include "caliper.chart" . }}
{{ include "caliper.labels" . | indent 4 }}
data:
  CALIPER_BIND_SUT: fabric:2.1.0
  CALIPER_BIND_SDK: 2.1.0
  CALIPER_BENCHCONFIG: microBenchMarkconfig.yaml
  CALIPER_NETWORKCONFIG: caliperNetworkConfig.yaml
  CALIPER_REPORT_PATH: report4peers4clientsBidding.html
  CALIPER_LOGGING_FORMATS-JSON: "{space:0}"
  CALIPER_WORKER_REMOTE: "true"
  CALIPER_WORKER_COMMUNICATION_METHOD: "mqtt"
  CALIPER_WORKER_COMMUNICATION_ADDRESS: "mqtt://caliper-mosquitto:1883"


