{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "caliper.serviceAccountName" . }}
  labels:
{{ include "caliper.labels" . | indent 4 }}
{{- end -}}
